App server/client tweaks
client:
 main sequence is now completely in shell builtins
 `message` and `error` functions
 notify-send support

server:
 more organized server code
 support client's `message` and `error` functions

diff --git a/uwsm-app b/uwsm-app
--- a/uwsm-app
+++ b/uwsm-app
@@ -1,67 +1,113 @@
 #!/bin/sh
 
 # Simple client for wayland-wm-app-daemon.service
-# A drop-in replacement for "wayland-session app"
+# A drop-in replacement for "uwsm app"
+# special arguments: ping, stop
 
 set -e
 
-# various read and write timeouts
+# timeout for all pipe operations
 TIMEOUT=10
 
 # assume uwsm is under the same name as us, without "-app"
-UWSM_NAME=${0##*/}
-UWSM_NAME=${UWSM_NAME%-app}
+SELF_NAME=${0##*/}
+UWSM_NAME=${SELF_NAME%-app}
 
 PIPE_IN="${XDG_RUNTIME_DIR}/uwsm-app-daemon-in"
 PIPE_OUT="${XDG_RUNTIME_DIR}/uwsm-app-daemon-out"
 
+DAEMON_UNIT=wayland-wm-app-daemon.service
+
 N='
 '
 
-# restart server if something is wrong with the pipes
+message(){
+	# print message "$1" to stdout
+	echo "$1"
+	# if notify-send is installed and stdout is not a terminal, also send notification
+	if [ ! -t 1 ] && command -v notify-send >/dev/null; then
+		notify-send -u normal -i info -a "${SELF_NAME}" "App message" "$1"
+	fi
+}
+
+error(){
+	# print message "$1" to stderr
+	echo "$1" >&2
+	# if notify-send is installed and stderr is not a terminal, also send notification
+	if [ ! -t 2 ] && command -v notify-send >/dev/null; then
+		notify-send -u critical -i error -a "${SELF_NAME}" "App failure" "$1"
+	fi
+	# if code is 141 (128+13, exit due to SIGPIPE), also restart daemon
+	if [ "${2:-1}" = "141" ]; then
+		systemctl --user restart "$DAEMON_UNIT" || true
+	fi
+	# exit with code $2
+	exit ${2:-1}
+}
+
+# fork timeout killer
+MAINPID=$$
+{
+	# send SIGPIPE to main process after timeout
+	sleep $TIMEOUT
+	if kill -0 $MAINPID 2>/dev/null; then
+		kill -13 $MAINPID
+	fi
+} &
+KILLER_PID=$!
+
+# trap SIGPIPE
+trap 'error "Timed out waiting for pipes!" 141' PIPE
+
+# restart server if pipes are missing or not pipes
 if [ ! -p "$PIPE_IN" ] || [ ! -p "$PIPE_OUT" ]; then
-	systemctl --user restart wayland-wm-app-daemon.service
-	PIPE_TIMEOUT=$TIMEOUT
+	systemctl --user restart "$DAEMON_UNIT"
 	# wait for pipes to become pipes
 	while [ ! -p "$PIPE_IN" ] && [ ! -p "$PIPE_OUT" ]; do
-		if [ "$PIPE_TIMEOUT" -le "0" ]; then
-			echo "Timed out waiting for pipes" >&2
-			exit 1
-		else
-			sleep 1
-			PIPE_TIMEOUT=$((PIPE_TIMEOUT - 1))
-		fi
+		sleep 1
 	done
 else
-	# check in background if server is not running and launch it
-	if ! systemctl --user is-active -q wayland-wm-app-daemon.service; then
-		systemctl --user restart wayland-wm-app-daemon.service
-	fi > /dev/null &
+	# start server in background
+	# this does nothing if it is already started
+	systemctl --user start "$DAEMON_UNIT" &
 fi
+
+# update message
+trap 'error "Timed out trying to write to ${PIPE_IN}!" 141' PIPE
 
 # write args to input pipe
 if [ "$#" = "0" ]; then
 	echo "No args given!" >&2
 	exit 1
 elif [ "$#" = "1" ] && [ "$1" = "ping" ]; then
-	timeout "$TIMEOUT" printf '%s' 'ping' > "$PIPE_IN"
+	printf '%s' 'ping' > "$PIPE_IN"
 elif [ "$#" = "1" ] && [ "$1" = "stop" ]; then
-	timeout "$TIMEOUT" printf '%s' 'stop' > "$PIPE_IN"
+	printf '%s' 'stop' > "$PIPE_IN"
 else
-	timeout "$TIMEOUT" printf '\0%s' app "$@" > "$PIPE_IN"
+	printf '\0%s' app "$@" > "$PIPE_IN"
 fi
 
+# update message
+trap 'error "Timed out trying to read from ${PIPE_OUT}!" 141' PIPE
+
 # read from output pipe
-CMDLINE=$(timeout $TIMEOUT cat "$PIPE_OUT")
+CMDLINE=
+while IFS='' read line; do
+	CMDLINE="${CMDLINE}${CMDLINE:+$N}${line}"
+done < "$PIPE_OUT"
+
+# kill timeout killer process and its sleep process
+kill $KILLER_PID $(ps --ppid $KILLER_PID -o pid= || true) &
 
 case "$CMDLINE" in
 pong)
-	echo pong
+	message pong
 	exit 0
 	;;
 '' | "$N")
-	echo "Received empty command" >&2
-	exit 1
+	error "Received empty command!"
 	;;
-*) eval "$CMDLINE" ;;
+*)
+	# run received commands
+	eval "$CMDLINE" ;;
 esac
